/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AutenticacaoRouteImport } from './routes/autenticacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PixPendenteRouteImport } from './routes/pix-pendente'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCpfRouteImport } from './routes/api/public/cpf'
import { Route as ApiPublicPixRouteImport } from './routes/api/public/pix'
import { Route as ApiPublicPixStatusRouteImport } from './routes/api/public/pix-status'
import { Route as ApiPublicReconcilePaymentsRouteImport } from './routes/api/public/reconcile-payments'
import { Route as ApiPublicUtmifyWebhookRouteImport } from './routes/api/public/utmify-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticacaoRoute = AutenticacaoRouteImport.update({
  id: '/autenticacao',
  path: '/autenticacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PixPendenteRoute = PixPendenteRouteImport.update({
  id: '/pix-pendente',
  path: '/pix-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCpfRoute = ApiPublicCpfRouteImport.update({
  id: '/api/public/cpf',
  path: '/api/public/cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixRoute = ApiPublicPixRouteImport.update({
  id: '/api/public/pix',
  path: '/api/public/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixStatusRoute = ApiPublicPixStatusRouteImport.update({
  id: '/api/public/pix-status',
  path: '/api/public/pix-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcilePaymentsRoute =
  ApiPublicReconcilePaymentsRouteImport.update({
    id: '/api/public/reconcile-payments',
    path: '/api/public/reconcile-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUtmifyWebhookRoute = ApiPublicUtmifyWebhookRouteImport.update({
  id: '/api/public/utmify-webhook',
  path: '/api/public/utmify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autenticacao': typeof AutenticacaoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/pix-pendente': typeof PixPendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/cpf': typeof ApiPublicCpfRoute
  '/api/public/pix': typeof ApiPublicPixRoute
  '/api/public/pix-status': typeof ApiPublicPixStatusRoute
  '/api/public/reconcile-payments': typeof ApiPublicReconcilePaymentsRoute
  '/api/public/utmify-webhook': typeof ApiPublicUtmifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autenticacao': typeof AutenticacaoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/pix-pendente': typeof PixPendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/cpf': typeof ApiPublicCpfRoute
  '/api/public/pix': typeof ApiPublicPixRoute
  '/api/public/pix-status': typeof ApiPublicPixStatusRoute
  '/api/public/reconcile-payments': typeof ApiPublicReconcilePaymentsRoute
  '/api/public/utmify-webhook': typeof ApiPublicUtmifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/autenticacao': typeof AutenticacaoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/pix-pendente': typeof PixPendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/cpf': typeof ApiPublicCpfRoute
  '/api/public/pix': typeof ApiPublicPixRoute
  '/api/public/pix-status': typeof ApiPublicPixStatusRoute
  '/api/public/reconcile-payments': typeof ApiPublicReconcilePaymentsRoute
  '/api/public/utmify-webhook': typeof ApiPublicUtmifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autenticacao'
    | '/auth'
    | '/checkout'
    | '/pagamento'
    | '/pix-pendente'
    | '/reset-password'
    | '/status'
    | '/admin'
    | '/api/public/cpf'
    | '/api/public/pix'
    | '/api/public/pix-status'
    | '/api/public/reconcile-payments'
    | '/api/public/utmify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autenticacao'
    | '/auth'
    | '/checkout'
    | '/pagamento'
    | '/pix-pendente'
    | '/reset-password'
    | '/status'
    | '/admin'
    | '/api/public/cpf'
    | '/api/public/pix'
    | '/api/public/pix-status'
    | '/api/public/reconcile-payments'
    | '/api/public/utmify-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/autenticacao'
    | '/auth'
    | '/checkout'
    | '/pagamento'
    | '/pix-pendente'
    | '/reset-password'
    | '/status'
    | '/_authenticated/admin'
    | '/api/public/cpf'
    | '/api/public/pix'
    | '/api/public/pix-status'
    | '/api/public/reconcile-payments'
    | '/api/public/utmify-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AutenticacaoRoute: typeof AutenticacaoRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  PagamentoRoute: typeof PagamentoRoute
  PixPendenteRoute: typeof PixPendenteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  ApiPublicCpfRoute: typeof ApiPublicCpfRoute
  ApiPublicPixRoute: typeof ApiPublicPixRoute
  ApiPublicPixStatusRoute: typeof ApiPublicPixStatusRoute
  ApiPublicReconcilePaymentsRoute: typeof ApiPublicReconcilePaymentsRoute
  ApiPublicUtmifyWebhookRoute: typeof ApiPublicUtmifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autenticacao': {
      id: '/autenticacao'
      path: '/autenticacao'
      fullPath: '/autenticacao'
      preLoaderRoute: typeof AutenticacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix-pendente': {
      id: '/pix-pendente'
      path: '/pix-pendente'
      fullPath: '/pix-pendente'
      preLoaderRoute: typeof PixPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cpf': {
      id: '/api/public/cpf'
      path: '/api/public/cpf'
      fullPath: '/api/public/cpf'
      preLoaderRoute: typeof ApiPublicCpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix': {
      id: '/api/public/pix'
      path: '/api/public/pix'
      fullPath: '/api/public/pix'
      preLoaderRoute: typeof ApiPublicPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-status': {
      id: '/api/public/pix-status'
      path: '/api/public/pix-status'
      fullPath: '/api/public/pix-status'
      preLoaderRoute: typeof ApiPublicPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-payments': {
      id: '/api/public/reconcile-payments'
      path: '/api/public/reconcile-payments'
      fullPath: '/api/public/reconcile-payments'
      preLoaderRoute: typeof ApiPublicReconcilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/utmify-webhook': {
      id: '/api/public/utmify-webhook'
      path: '/api/public/utmify-webhook'
      fullPath: '/api/public/utmify-webhook'
      preLoaderRoute: typeof ApiPublicUtmifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AutenticacaoRoute: AutenticacaoRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  PagamentoRoute: PagamentoRoute,
  PixPendenteRoute: PixPendenteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  ApiPublicCpfRoute: ApiPublicCpfRoute,
  ApiPublicPixRoute: ApiPublicPixRoute,
  ApiPublicPixStatusRoute: ApiPublicPixStatusRoute,
  ApiPublicReconcilePaymentsRoute: ApiPublicReconcilePaymentsRoute,
  ApiPublicUtmifyWebhookRoute: ApiPublicUtmifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
